version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ADMIN_PASSWORD=changeme
    volumes:
      - ./uploads:/app/uploads
      - ./app/data.db:/app/app/data.db
    ports:
      - "8000:8000"
    depends_on:
      - analysis
  analysis:
    build:
      context: analysis_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
