version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - OPENROUTER_API_KEY
        - OPENROUTER_MODEL
    environment:
      - ADMIN_PASSWORD=changeme
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
    volumes:
      - ./uploads:/app/uploads
      - ./app/data.db:/app/app/data.db
    ports:
      - "8000:8000"
    depends_on:
      - analysis
  analysis:
    build:
      context: analysis_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
