name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
          pip install pytest
      - name: Lint backend
        run: flake8 app
      - name: Run backend tests
        run: pytest -q

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        run: npm ci --legacy-peer-deps
        working-directory: frontend
      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev
      - name: Build analysis service
        run: cargo build --release
        working-directory: analysis_service

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          tags: linchat-backend:ci
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build analysis image
        uses: docker/build-push-action@v5
        with:
          context: analysis_service
          file: analysis_service/Dockerfile
          tags: linchat-analysis:ci
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: linchat-frontend:ci
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
