name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      - name: Lint backend
        run: flake8 app

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        run: npm ci
        working-directory: frontend
      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build analysis service
        run: cargo build --release
        working-directory: analysis_service

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -t linchat-backend -f Dockerfile .
      - name: Build analysis image
        run: docker build -t linchat-analysis -f analysis_service/Dockerfile analysis_service
      - name: Build frontend image
        run: docker build -t linchat-frontend -f frontend/Dockerfile frontend
